# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mat_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Marriage proposal!!', max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Please enter the details of yourself, and the detail you would like the other party to know. You have a limit of 2300 characters')),
                ('email_address', models.CharField(help_text='Enter a Valid email address for contact Purpose', max_length=100)),
                ('phone_contact', models.CharField(max_length=20)),
                ('your_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=6)),
                ('your_age', models.IntegerField(default=23)),
                ('your_qualification', models.CharField(max_length=200)),
                ('search_age', models.CharField(choices=[('one', '18-23'), ('two', '24-29'), ('three', '30-35'), ('four', '36-41'), ('five', '41+')], default='one', max_length=5)),
                ('search_qualification', models.CharField(max_length=200)),
                ('search_settled', models.CharField(max_length=200)),
                ('detail_privacy', models.BooleanField(help_text='Your Information will be hidden')),
                ('terms_and_conditions', models.BooleanField(default=True, help_text='Do you Agree with the terms and conditions')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
