# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import matrimonial.models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mat_info',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mat_info',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=matrimonial.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='mat_info',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
