# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 12:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial', '0002_auto_20170304_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='mat_info',
            name='Draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mat_info',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 3, 5, 12, 17, 44, 337802, tzinfo=utc)),
        ),
    ]
