# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial', '0012_auto_20170313_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mat_info',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 3, 21, 13, 37, 40, 357056, tzinfo=utc)),
        ),
    ]
