# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_database',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job_database',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 3, 5, 12, 10, 15, 780439, tzinfo=utc)),
        ),
    ]
