# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 01:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0013_auto_20170312_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_database',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 3, 13, 1, 50, 5, 589527, tzinfo=utc)),
        ),
    ]
