# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_info',
            name='detail',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questions_info',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 3, 12, 18, 11, 57, 777065, tzinfo=utc)),
        ),
    ]
